// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registro_de_Vacunados.Services;

namespace Registro_de_Vacunados.Migrations
{
    [DbContext(typeof(VacunadosDbContext))]
    [Migration("20220113194540_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Registro_de_Vacunados.Entities.RvacunadosTab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosis1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosis2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosis3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaRefuerzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lote1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lote2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lote3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoteRefuerzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Refuerzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("progreso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RvacunadosTab");
                });
#pragma warning restore 612, 618
        }
    }
}
